framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - messenger.middleware.fire_events
                    - messenger.middleware.validation
                    - messenger.middleware.doctrine_transaction
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - messenger.middleware.doctrine_transaction
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
