<?php
declare(strict_types = 1);

namespace Dredd;

/**
 * This class is autogenerated. DO NOT MODIFY
 */
final class Names
{
    const REGISTER_POST_201 = "User > /api/register > POST > 201 > application/json";
    const REGISTER_POST_400 = "User > /api/register > POST > 400 > application/json";
    const USER_CONFIRM_EMAIL_204 = "User > /api/user/confirm-email > Confirm email with confirmation token. > 204";
    const USER_CONFIRM_EMAIL_400 = "User > /api/user/confirm-email > Confirm email with confirmation token. > 400";
    const USER_CHANGE_PASSWORD_204 = "User > /api/user/change-password > Changes current user's password. > 204";
    const USER_CHANGE_PASSWORD_400 = "User > /api/user/change-password > Changes current user's password. > 400";
    const USER_CHANGE_PASSWORD_401 = "User > /api/user/change-password > Changes current user's password. > 401";
    const USER_CHANGE_EMAIL_204 = "User > /api/user/change-email > Changes current user's email. > 204";
    const USER_CHANGE_EMAIL_400 = "User > /api/user/change-email > Changes current user's email. > 400";
    const USER_CHANGE_EMAIL_401 = "User > /api/user/change-email > Changes current user's email. > 401";
    const USER_CHANGE_NAME_204 = "User > /api/user/change-name > Changes current user's name. > 204";
    const USER_CHANGE_NAME_400 = "User > /api/user/change-name > Changes current user's name. > 400";
    const USER_CHANGE_NAME_401 = "User > /api/user/change-name > Changes current user's name. > 401";
    const USER_ME_200 = "User > /api/user/me > Returns current user > 200 > application/json";
    const USER_ME_401 = "User > /api/user/me > Returns current user > 401 > application/json";
    const USER_200 = "User > /api/user > Returns list of users > 200 > application/json";
    const USER_401 = "User > /api/user > Returns list of users > 401 > application/json";
    const LOGIN_CHECK_POST_200 = "Auth > /api/login_check > POST > 200 > application/json";
    const LOGIN_CHECK_POST_401 = "Auth > /api/login_check > POST > 401 > application/json";
}